# Generated by Django 4.1.7 on 2023-04-09 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_subscribers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribers',
            old_name='auth_token',
            new_name='email_token',
        ),
    ]
