# Generated by Django 4.1.7 on 2023-04-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_auth_token_subscribers_email_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='genre',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='genre',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
