# Generated by Django 4.1.7 on 2023-04-17 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_subscribers_genre_alter_blogmodel_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribers',
            name='genre',
        ),
    ]
